/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as FlyerHomeIdRouteImport } from './routes/flyer.$homeId'
import { Route as HomesIndexRouteImport } from './routes/homes.index'
import { Route as HomesHomeIdRouteImport } from './routes/homes.$homeId'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardLeadsRouteImport } from './routes/_authenticated/dashboard.leads'
import { Route as AuthenticatedDashboardTeamRouteImport } from './routes/_authenticated/dashboard.team'
import { Route as AuthenticatedDashboardListingsIndexRouteImport } from './routes/_authenticated/dashboard.listings.index'
import { Route as AuthenticatedDashboardListingsHomeIdRouteImport } from './routes/_authenticated/dashboard.listings.$homeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FlyerHomeIdRoute = FlyerHomeIdRouteImport.update({
  id: '/flyer/$homeId',
  path: '/flyer/$homeId',
  getParentRoute: () => rootRouteImport,
} as any)
const HomesIndexRoute = HomesIndexRouteImport.update({
  id: '/homes/',
  path: '/homes/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomesHomeIdRoute = HomesHomeIdRouteImport.update({
  id: '/homes/$homeId',
  path: '/homes/$homeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLeadsRoute =
  AuthenticatedDashboardLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTeamRoute =
  AuthenticatedDashboardTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardListingsIndexRoute =
  AuthenticatedDashboardListingsIndexRouteImport.update({
    id: '/listings/',
    path: '/listings/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardListingsHomeIdRoute =
  AuthenticatedDashboardListingsHomeIdRouteImport.update({
    id: '/listings/$homeId',
    path: '/listings/$homeId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/financing': typeof FinancingRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/flyer/$homeId': typeof FlyerHomeIdRoute
  '/homes/$homeId': typeof HomesHomeIdRoute
  '/blog/': typeof BlogIndexRoute
  '/homes/': typeof HomesIndexRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/team': typeof AuthenticatedDashboardTeamRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/listings/$homeId': typeof AuthenticatedDashboardListingsHomeIdRoute
  '/dashboard/listings/': typeof AuthenticatedDashboardListingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/financing': typeof FinancingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/flyer/$homeId': typeof FlyerHomeIdRoute
  '/homes/$homeId': typeof HomesHomeIdRoute
  '/blog': typeof BlogIndexRoute
  '/homes': typeof HomesIndexRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/team': typeof AuthenticatedDashboardTeamRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/listings/$homeId': typeof AuthenticatedDashboardListingsHomeIdRoute
  '/dashboard/listings': typeof AuthenticatedDashboardListingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/financing': typeof FinancingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/flyer/$homeId': typeof FlyerHomeIdRoute
  '/homes/$homeId': typeof HomesHomeIdRoute
  '/blog/': typeof BlogIndexRoute
  '/homes/': typeof HomesIndexRoute
  '/_authenticated/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/_authenticated/dashboard/team': typeof AuthenticatedDashboardTeamRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/listings/$homeId': typeof AuthenticatedDashboardListingsHomeIdRoute
  '/_authenticated/dashboard/listings/': typeof AuthenticatedDashboardListingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/faq'
    | '/financing'
    | '/dashboard'
    | '/blog/$slug'
    | '/flyer/$homeId'
    | '/homes/$homeId'
    | '/blog/'
    | '/homes/'
    | '/dashboard/leads'
    | '/dashboard/team'
    | '/dashboard/'
    | '/dashboard/listings/$homeId'
    | '/dashboard/listings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/faq'
    | '/financing'
    | '/blog/$slug'
    | '/flyer/$homeId'
    | '/homes/$homeId'
    | '/blog'
    | '/homes'
    | '/dashboard/leads'
    | '/dashboard/team'
    | '/dashboard'
    | '/dashboard/listings/$homeId'
    | '/dashboard/listings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/faq'
    | '/financing'
    | '/_authenticated/dashboard'
    | '/blog/$slug'
    | '/flyer/$homeId'
    | '/homes/$homeId'
    | '/blog/'
    | '/homes/'
    | '/_authenticated/dashboard/leads'
    | '/_authenticated/dashboard/team'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/listings/$homeId'
    | '/_authenticated/dashboard/listings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  FinancingRoute: typeof FinancingRoute
  BlogSlugRoute: typeof BlogSlugRoute
  FlyerHomeIdRoute: typeof FlyerHomeIdRoute
  HomesHomeIdRoute: typeof HomesHomeIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  HomesIndexRoute: typeof HomesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flyer/$homeId': {
      id: '/flyer/$homeId'
      path: '/flyer/$homeId'
      fullPath: '/flyer/$homeId'
      preLoaderRoute: typeof FlyerHomeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homes/': {
      id: '/homes/'
      path: '/homes'
      fullPath: '/homes/'
      preLoaderRoute: typeof HomesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homes/$homeId': {
      id: '/homes/$homeId'
      path: '/homes/$homeId'
      fullPath: '/homes/$homeId'
      preLoaderRoute: typeof HomesHomeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/leads': {
      id: '/_authenticated/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof AuthenticatedDashboardLeadsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/team': {
      id: '/_authenticated/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof AuthenticatedDashboardTeamRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/listings/': {
      id: '/_authenticated/dashboard/listings/'
      path: '/listings'
      fullPath: '/dashboard/listings/'
      preLoaderRoute: typeof AuthenticatedDashboardListingsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/listings/$homeId': {
      id: '/_authenticated/dashboard/listings/$homeId'
      path: '/listings/$homeId'
      fullPath: '/dashboard/listings/$homeId'
      preLoaderRoute: typeof AuthenticatedDashboardListingsHomeIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardLeadsRoute: typeof AuthenticatedDashboardLeadsRoute
  AuthenticatedDashboardTeamRoute: typeof AuthenticatedDashboardTeamRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardListingsHomeIdRoute: typeof AuthenticatedDashboardListingsHomeIdRoute
  AuthenticatedDashboardListingsIndexRoute: typeof AuthenticatedDashboardListingsIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardLeadsRoute: AuthenticatedDashboardLeadsRoute,
    AuthenticatedDashboardTeamRoute: AuthenticatedDashboardTeamRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardListingsHomeIdRoute:
      AuthenticatedDashboardListingsHomeIdRoute,
    AuthenticatedDashboardListingsIndexRoute:
      AuthenticatedDashboardListingsIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  FinancingRoute: FinancingRoute,
  BlogSlugRoute: BlogSlugRoute,
  FlyerHomeIdRoute: FlyerHomeIdRoute,
  HomesHomeIdRoute: HomesHomeIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  HomesIndexRoute: HomesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
